import { 
  GameState, 
  PlayerState, 
  Card,
  CycleCard,
  // ✅ BASIC CARDS que SÍ EXISTEN:
  ULTIMA_OPORTUNIDAD,
  MERCENARIO_AGIL,
  EXPLORADOR_ASTUTO,
  ASESINO_SILENCIOSO,
  GUARDIAN_NOVATO,
  REFLEJO_RAPIDO,
  CUCHILLA_ENVENENADA,
  EXPLORADOR_AUDAZ,
  ESCRIBA_ESTUDIOSO,
  FLECHA_CERTEZA,
  DUELISTA_EXPERTO,
  COMERCIANTE_SAGAZ,
  DISPARO_CERTERO,
  BERSERKER_HERIDO,
  RECARGA_RAPIDA,
  MOMENTO_CRUCIAL,
  SOLDADO_VETERANO,
  INTERCEPCION_RAPIDA,
  CURANDERO_SABIO,
  CENTINELA_VIGILANTE,
  LLAMA_IMPURA,
  MAESTRO_DE_ARMAS,
  ACECHADOR_NOCTURNO,
  PALABRA_DE_PODER,
  VAMPIRO_ANCESTRAL,
  COLOSO_DE_HIERRO,
  INGENIERA_ASTUTA,
  TORMENTA_DE_ACERO,
  GOLPE_DEVASTADOR,
  CAMPEON_CAIDO,
  SENOR_DE_LA_GUERRA,
  RITUAL_DE_RENOVACION,
  TITAN_PRIMORDIAL,
  APOCALIPSIS,
  
  // ✅ CLASS CARDS que SÍ EXISTEN:
  ESPECIMEN_PERFECTO,
  ESPECIMEN_PERFECTO_FINAL_STAND,
  ESPECIMEN_PERFECTO_EVOLUCIONADO,
  EXPLORADOR_INFECTADO,
  RECOLECTOR_DE_TEJIDOS,
  NECROFAGO_HAMBRIENTO,
  RITUAL_MENOR,
  ANATOMISTA_EXPERTO,
  INVOCACION_SINIESTRA,
  PERFECCIONISTA_OBSESIVO,
  RITUAL_DE_PERFECCION,
  MAESTRO_NECROMANTICO,
  EVOLUCION_PERFECTA,
  APRENDIZ_ERRATICO,
  MAGO_DEL_CAOS,
  RITUAL_CAOTICO,
  MERCADER_LOCO,
  MANIPULADOR_DEL_DESTINO,
  PORTAL_INESTABLE,
  CAOS_CONTROLADO,
  SENOR_DEL_CAOS,
  TORMENTA_IMPREDECIBLE,
  REALIDAD_FRACTURADA,
  EXPLORADOR_CREPUSCULAR,
  RITUAL_DEL_AMANECER,
  VIDENTE_LUNAR,
  CAMBIAFORMAS_LUNAR,
  INVOCADOR_DE_ECLIPSE,
  GUARDIAN_DEL_EQUILIBRIO,
  MOMENTO_PERFECTO,
  MAESTRO_DEL_TIEMPO,
  ECLIPSE_ETERNO,
  CONVERGENCIA_CELESTIAL,
  FANATICO_DESESPERADO,
  BERSERKER_SANGUINARIO,
  CAZADOR_DE_RECOMPENSAS,
  RITUAL_SANGRIENTO,
  GUERRERO_HERIDO,
  SENOR_DE_LA_SANGRE,
  PACTO_DE_PODER,
  PACTO_FINAL,
  FRENESI_FINAL,
  AVATAR_DE_LA_DESTRUCCION
} from '@infradeck/shared'

// ✅ CARD REGISTRY: Permitir tanto Card como CycleCard
const ALL_CARDS: Record<string, Card | CycleCard> = {
  // Basic Cards (33)
  [ULTIMA_OPORTUNIDAD.id]: ULTIMA_OPORTUNIDAD,
  [MERCENARIO_AGIL.id]: MERCENARIO_AGIL,
  [EXPLORADOR_ASTUTO.id]: EXPLORADOR_ASTUTO,
  [ASESINO_SILENCIOSO.id]: ASESINO_SILENCIOSO,
  [GUARDIAN_NOVATO.id]: GUARDIAN_NOVATO,
  [REFLEJO_RAPIDO.id]: REFLEJO_RAPIDO,
  [CUCHILLA_ENVENENADA.id]: CUCHILLA_ENVENENADA,
  [EXPLORADOR_AUDAZ.id]: EXPLORADOR_AUDAZ,
  [ESCRIBA_ESTUDIOSO.id]: ESCRIBA_ESTUDIOSO,
  [FLECHA_CERTEZA.id]: FLECHA_CERTEZA,
  [DUELISTA_EXPERTO.id]: DUELISTA_EXPERTO,
  [COMERCIANTE_SAGAZ.id]: COMERCIANTE_SAGAZ,
  [DISPARO_CERTERO.id]: DISPARO_CERTERO,
  [BERSERKER_HERIDO.id]: BERSERKER_HERIDO,
  [RECARGA_RAPIDA.id]: RECARGA_RAPIDA,
  [MOMENTO_CRUCIAL.id]: MOMENTO_CRUCIAL,
  [SOLDADO_VETERANO.id]: SOLDADO_VETERANO,
  [INTERCEPCION_RAPIDA.id]: INTERCEPCION_RAPIDA,
  [CURANDERO_SABIO.id]: CURANDERO_SABIO,
  [CENTINELA_VIGILANTE.id]: CENTINELA_VIGILANTE,
  [LLAMA_IMPURA.id]: LLAMA_IMPURA,
  [MAESTRO_DE_ARMAS.id]: MAESTRO_DE_ARMAS,
  [ACECHADOR_NOCTURNO.id]: ACECHADOR_NOCTURNO,
  [PALABRA_DE_PODER.id]: PALABRA_DE_PODER,
  [VAMPIRO_ANCESTRAL.id]: VAMPIRO_ANCESTRAL,
  [COLOSO_DE_HIERRO.id]: COLOSO_DE_HIERRO,
  [INGENIERA_ASTUTA.id]: INGENIERA_ASTUTA,
  [TORMENTA_DE_ACERO.id]: TORMENTA_DE_ACERO,
  [GOLPE_DEVASTADOR.id]: GOLPE_DEVASTADOR,
  [CAMPEON_CAIDO.id]: CAMPEON_CAIDO,
  [SENOR_DE_LA_GUERRA.id]: SENOR_DE_LA_GUERRA,
  [RITUAL_DE_RENOVACION.id]: RITUAL_DE_RENOVACION,
  [TITAN_PRIMORDIAL.id]: TITAN_PRIMORDIAL,
  [APOCALIPSIS.id]: APOCALIPSIS,
  
  // Class Cards (incluye Card y CycleCard)
  [ESPECIMEN_PERFECTO.id]: ESPECIMEN_PERFECTO,
  [ESPECIMEN_PERFECTO_FINAL_STAND.id]: ESPECIMEN_PERFECTO_FINAL_STAND,
  [ESPECIMEN_PERFECTO_EVOLUCIONADO.id]: ESPECIMEN_PERFECTO_EVOLUCIONADO,
  [EXPLORADOR_INFECTADO.id]: EXPLORADOR_INFECTADO,
  [RECOLECTOR_DE_TEJIDOS.id]: RECOLECTOR_DE_TEJIDOS,
  [NECROFAGO_HAMBRIENTO.id]: NECROFAGO_HAMBRIENTO,
  [RITUAL_MENOR.id]: RITUAL_MENOR,
  [ANATOMISTA_EXPERTO.id]: ANATOMISTA_EXPERTO,
  [INVOCACION_SINIESTRA.id]: INVOCACION_SINIESTRA,
  [PERFECCIONISTA_OBSESIVO.id]: PERFECCIONISTA_OBSESIVO,
  [RITUAL_DE_PERFECCION.id]: RITUAL_DE_PERFECCION,
  [MAESTRO_NECROMANTICO.id]: MAESTRO_NECROMANTICO,
  [EVOLUCION_PERFECTA.id]: EVOLUCION_PERFECTA,
  [APRENDIZ_ERRATICO.id]: APRENDIZ_ERRATICO,
  [MAGO_DEL_CAOS.id]: MAGO_DEL_CAOS,
  [RITUAL_CAOTICO.id]: RITUAL_CAOTICO,
  [MERCADER_LOCO.id]: MERCADER_LOCO,
  [MANIPULADOR_DEL_DESTINO.id]: MANIPULADOR_DEL_DESTINO,
  [PORTAL_INESTABLE.id]: PORTAL_INESTABLE,
  [CAOS_CONTROLADO.id]: CAOS_CONTROLADO,
  [SENOR_DEL_CAOS.id]: SENOR_DEL_CAOS,
  [TORMENTA_IMPREDECIBLE.id]: TORMENTA_IMPREDECIBLE,
  [REALIDAD_FRACTURADA.id]: REALIDAD_FRACTURADA,
  [EXPLORADOR_CREPUSCULAR.id]: EXPLORADOR_CREPUSCULAR, // ✅ CycleCard
  [RITUAL_DEL_AMANECER.id]: RITUAL_DEL_AMANECER,
  [VIDENTE_LUNAR.id]: VIDENTE_LUNAR,
  [CAMBIAFORMAS_LUNAR.id]: CAMBIAFORMAS_LUNAR, // ✅ CycleCard
  [INVOCADOR_DE_ECLIPSE.id]: INVOCADOR_DE_ECLIPSE,
  [GUARDIAN_DEL_EQUILIBRIO.id]: GUARDIAN_DEL_EQUILIBRIO,
  [MOMENTO_PERFECTO.id]: MOMENTO_PERFECTO,
  [MAESTRO_DEL_TIEMPO.id]: MAESTRO_DEL_TIEMPO,
  [ECLIPSE_ETERNO.id]: ECLIPSE_ETERNO,
  [CONVERGENCIA_CELESTIAL.id]: CONVERGENCIA_CELESTIAL,
  [FANATICO_DESESPERADO.id]: FANATICO_DESESPERADO,
  [BERSERKER_SANGUINARIO.id]: BERSERKER_SANGUINARIO,
  [CAZADOR_DE_RECOMPENSAS.id]: CAZADOR_DE_RECOMPENSAS,
  [RITUAL_SANGRIENTO.id]: RITUAL_SANGRIENTO,
  [GUERRERO_HERIDO.id]: GUERRERO_HERIDO,
  [SENOR_DE_LA_SANGRE.id]: SENOR_DE_LA_SANGRE,
  [PACTO_DE_PODER.id]: PACTO_DE_PODER,
  [PACTO_FINAL.id]: PACTO_FINAL,
  [FRENESI_FINAL.id]: FRENESI_FINAL,
  [AVATAR_DE_LA_DESTRUCCION.id]: AVATAR_DE_LA_DESTRUCCION
}

// ...imports y ALL_CARDS...

// ✅ AÑADIR EXPORT: La función que falta exportar
export function getCardById(id: string): Card | CycleCard | undefined {
  return ALL_CARDS[id]
}

// ✅ Resto de funciones exportadas correctamente
export function getCurrentPlayer(gameState: GameState, playerIndex: number): PlayerState {
  return gameState.players[playerIndex]
}

export function getOpponent(gameState: GameState, playerIndex: number): PlayerState {
  return gameState.players[1 - playerIndex]
}

export function isPlayerTurn(gameState: GameState, playerIndex: number): boolean {
  return gameState.turn.currentPlayerIndex === playerIndex
}

export function formatGameTime(startTime: Date): string {
  const elapsed = Date.now() - startTime.getTime()
  const minutes = Math.floor(elapsed / 60000)
  const seconds = Math.floor((elapsed % 60000) / 1000)
  return `${minutes}:${seconds.toString().padStart(2, '0')}`
}

export function getPlayerStatus(player: PlayerState) {
  return {
    isLowLife: player.life <= 5,
    isHighLife: player.life >= 15,
    isLowMana: player.mana <= 2, 
    isHighMana: player.mana >= 8,
    handSize: player.hand.length,
    fieldSize: player.board.length
  }
}

export function getAllCards(): (Card | CycleCard)[] {
  return Object.values(ALL_CARDS)
}

export function getCardsByClass(classType?: string): (Card | CycleCard)[] {
  return Object.values(ALL_CARDS).filter(card => 
    card.classType === classType || (!card.classType && !classType)
  )
}